#!/bin/sh

##
# HubSpot API companies download
#
# Syntax:
#
#     hubspot-api-companies-download
#
# This tool is for [HubSpot](https://hubspot.com) account users.
# This tool connects to the HubSpot API and downloads companies.
#
# The output is a series of JSON files with file names that
# show the "visitor identification" (vid) after number and
# the requested record count limit.
#
# Example output file names:
#
#     companies-after-0-limit-100.json
#     companies-after-3051-limit-100.json
#     companies-after-4753-limit-100.json
#
# This tool also combines the files' companies into one file name:
#
#     companies.json
#
# Author: joel@joelparkerhenderson.com
##

set -euf

# Include https://github.com/SixArm/posix-shell-script-kit
. "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"

##
#
# HubSpot API
#
##

# Get HubSpot API URI to download
# Syntax: uri $after $limit 
uri() {
    after="$1"
    limit="$2"
    echo "https://api.hubapi.com/crm/v3/objects/companies?hapikey=$HUBSPOT_API_KEY&"$([ "$after" = "0" ] && echo "" || echo "after=$after&")"limit=$limit"
}

# Get name to save the data file
# Syntax: file_name $after $limit
file_name() {
    out "companies-after-$1-limit-$2.json"   
}

# Get the file's HubSpot cursor identifier
# Syntax: file_paging_next_after $file_name
file_paging_next_after() {
    jq -r '.paging.next.after' "$1"
}

# Combine all the response companies files into one big file
# Syntax: file_join
file_join() {
    jq -s 'reduce .[].results as $item ([]; . + $item)' companies-after-*-limit-*.json > companies.json
}

# Verify preflight
# Syntax: preflight
preflight() {
    [ -z ${HUBSPOT_API_KEY+x} ] && die "Environment needed: HUBSPOT_API_KEY"
    command_exists_or_die curl
    command_exists_or_die jq
}

# Main function
# Syntax: main
main() {
    after=0
    limit=100
    while true; do
        file_name=$(file_name $after $limit)
        uri=$(uri $after $limit)
        test -e "$file_name" || curl -s "$uri" > "$file_name"
        after=$(file_paging_next_after "$file_name")
        if [ "$after" = "null" ]; then
            break
        fi
    done
    file_join
}

preflight
main
exit 0
